### ISSUE TITLE
Popup window to check/uncheck audio effects

### ISSUE THREAD

**Issue by Rhys-sg** [WhitmanCS370/Johns-Frends#106]
playScreen(CommanderObject, Arguments):

**Comment by tater-tot25** [comment]
You can assume you will be passed a list of sound names, and a commander object. These just need to be stored and passed to me later. Your menu needs to create a PlaybackOptions object and pass it to me. So the resulting call will look like playMenu(soundNames, commander, playbackOptions).

**Comment by tater-tot25** [comment]
Thank you Rhys!!!
