### ISSUE TITLE
Playback option to save edits as new

### ISSUE THREAD

**Issue by samuelsl02** [WhitmanCS370/Johns-Frends#44]
--save-new  or -s when audio edits

**Comment by Rhys-sg** [comment]
Course of events:

1.	The user selects sound(s)
2.	The user selects the editing method(s)
3.	The user selects that they want to save the processed sound
4.	The user selects if they want to replace or save the sound as a new file
a.	If they select “save as a new file,” the user selects where they want to save the file
b.	If they select “save as a new file,” the user selects a name for the new file

**Comment by Rhys-sg** [comment]
Exceptions to consider:

For all steps, if the parameter list of inputs is incomplete, the interface will give an error specifying what is missing and the total list of required inputs. It will allow users to reinput everything or just what they are missing. In some cases (specified below), the interface just needs to prompt the user with yes or no (Y/N).

•	For step 1), if the user does not select a sound, the interface will read an error, list the available sounds, and prompt the user to specify the sound(s).
•	For step 1), if the sound does not exist in the archive, the interface will read an error, list the available sounds, and prompt the user to specify the sound(s). 
•	For step 2), if the user does not specify editing methods, the interface will read an error, list the available editing methods, and prompt the user to specify the editing method(s)
•	For step 2), if the user specifies editing method(s) that are not implemented, the interface will read an error, list the available editing methods, and prompt the user to respecify the editing method(s)
•	For step 2), if the user specifies two editing methods that conflict, the interface will read an error, list the available editing methods, and prompt the user to respecify the editing method(s)—there are no cases yet, but may be in the future
•	For step 3/4), if the user does not specify that they want to save the edited file but selects that they either want to replace or save the edited sound, the interface will read an error and ask if they want to save the sound (Y/N)
•	For step 3/4), if the user does not specify that they want to save the edited file but specifies where they want to save the edited file, the interface will read an error and ask if they want to save the sound (Y/N)
•	For step 4), if the user specifies that they want to save as new but not where, the interface will read an error, and prompts the user to specify where they would like to save it. The interface also asks if they would instead like to replace the file.
•	For step 4), if the user specifies that they want to save as new but not the name, the interface will read an error, and prompts the user to specify the new name. The interface also asks if they would instead like to replace the file.
•	For step 4), if the user specifies a directory that is not available, the interface will read an error, list the available directories, and prompt the user to specify the directory.

**Comment by Rhys-sg** [comment]
Considerations:

• We should use the "strategy pattern" and keep the editing methods separate.
• We should keep in mind that we will implement more interfaces later.
• We already have “-r” to reverse audio, so specifying “replace file” would have to be a different command—maybe “-re”. Instead of having shortened commands, we might want to only use full-length commands (“—reverse”) to make them less confusing/avoid conflicts. Another approach might be to use the same command but have the context determine its function. However, I think the second approach would be very confusing for the user and hard to maintain.

**Comment by Rhys-sg** [comment]
Should we specify if they want to save a sound to replace the “-p” or “—play” prompt at the beginning with “-e” or “—edit” to change from “play mode” to “edit mode” to make it feel more like an editor?

**Comment by LeedsJohn** [comment]
See #86 for continued discussion
