### ISSUE TITLE
Allow saving files from elsewhere in the filesystem

### ISSUE THREAD

**Issue by samuelsl02** [WhitmanCS370/Johns-Frends#60]
Allow users to upload files from their system to the repository; a path to the sound is saved in a static dictionary rather than the sound itself being copied. whenever a user specifies a sound to use, if it's not in the native sounds directory the dictionary is searched and the file is played from its current location

**Comment by LeedsJohn** [comment]
Check out the `src/storage_commander.py` file - at the moment, if someone adds a sound to the archive and it isn't already in the `sounds/` directory, a copy is created in `sounds/`.

However, if we're going to expand in the direction of more audio effects it might make sense to let users apply audio effects to files that are not in the archive - let me know what you think!

**Comment by samuelsl02** [comment]
This has been resolved with the new filesystem; `add` can import files from anywhere
