### ISSUE TITLE
When playing in parallel, both sounds last only as long as the shortest sound.

### ISSUE THREAD

**Issue by Rhys-sg** [WhitmanCS370/Johns-Frends#78]
To recreate:

1. python src/cli.py add ./sounds/toaster.wav
2. python src/cli.py add ./sounds/coffee.wav
3. python src/cli.py play toaster coffee -p 

toaster.wav is longer than coffee.wav, but only lasts as long as coffee.wav

**Comment by Rhys-sg** [comment]
This implementation does not work, but it might be a start: 

while any([play_obj.is_playing() for play_obj in play_objs]):
    pass

for play_obj in play_objs:
    play_obj.stop_all()

**Comment by LeedsJohn** [comment]
@Rhys-sg Interesting, I wasn't able to replicate this.  Did someone fix it?  Or I wonder if works on unix but not windows?
