### ISSUE TITLE
Make transposing not create a new file

### ISSUE THREAD

**Issue by samuelsl02** [WhitmanCS370/Johns-Frends#80]
Right now, the easiest way to work with the librosa interface is to have it make a new file that we open again. That shouldn't happen - it would be nice if we could directly have the y and stepsize translate to wave options.

**Comment by LeedsJohn** [comment]
Python has a [tempfile](https://docs.python.org/3/library/tempfile.html) library.  It would be nice if we don't need to create a file at all, but I'll take a look at using `tempfile` so we don't continually rewrite the same filename.

**Comment by LeedsJohn** [comment]
If anyone looks at this issue, they should see this development branch:

https://github.com/WhitmanCS370/Johns-Frends/tree/refactor-audio-effects

With this implementation, transposing no longer creates a dummy file (but transposing is broken).

**Comment by LeedsJohn** [comment]
[Here's a link to the current implementation of transpose.](https://github.com/WhitmanCS370/Johns-Frends/blob/6a6a22ba571fe18fb35471f5f07155df9f4505d4/src/audio_edits.py#L95-L105)

It still uses a tempfile, but I feel like it's relatively hidden away from people using the `audio_edits` module so I feel like it's okay for now.  I'm going to close this for now, but we can always come back to this if anyone has a better idea.
